### ISSUE TITLE
[E-Tron] Condition for two temples

### ISSUE THREAD

**Issue by twicki** [nalkpas/hand-simulator#2]
currently, the condition for two temple & thing hand is [(see here)](https://github.com/nalkpas/hand-simulator/blob/763974f9432c90703d79e4c9940ed190c380a4bc/eldrazi_tron.py#L34):
`(temples + has_Map >= 2) * (lands < (7 - j))`
This could be a 1 temple, 1 map N spells hand and should be discarded. 

I think the proper implementation would be 
`((temples >=2) or ((lands >=2)*(temples + has_Map >= 2)))* (lands < (7 - j))`

**Comment by nalkpas** [comment]
Hey, I was counting Map as an Eldrazi Temple for that category since it still contributes to draws like t3 Smasher or t4 Endbringer. You're right I should also have checked that the hand has more than two lands before counting Map, but since it has to have at least 1 Temple that shouldn't be a huge deal. I'll change it to (temples + has_Map * (lands >= 2) >= 2) * (lands < (7 - j)), probably.
